export const CONFIG_LOAD = "CONFIG_LOAD";
export const CONFIG_LOADED = "CONFIG_LOADED";
export const CONFIG_ROOT_FOUND = "CONFIG_ROOT_FOUND";
export const CONFIG_PACKAGE_FOUND = "CONFIG_PACKAGE_DIR_FOUND";
