settings:
  import/ignore:
    - '**/node_modules/**'
env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  react/prop-types:
    - 0
  indent:
    - error
    - 2
  space-before-function-paren:
    - warn
    - never
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - vars: 'local'
      varsIgnorePattern: '^_'
      args: 'none'
      ignoreRestSiblings: true
