
export const ADD_UPDATED_LOG= "ADD_UPDATED_LOG";

export const CHANGE_BUTTON_STATUS = "CHANGE_BUTTON_STATUS";

export const DEVELOPMENT_ENV_CHANGE = "DEVELOPMENT_ENV_CHANGE";

export const DEVELOPMENT_LOG = "DEVELOPMENT_LOG";

